# Generated by Django 5.0.4 on 2024-04-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='produkcje',
            name='ID_Kategorii',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.kategorie'),
            preserve_default=False,
        ),
    ]
