# Generated by Django 5.0.4 on 2024-06-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_kategorie_produkcje_id_kategorii'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='do_obejrzenia',
            options={'verbose_name_plural': 'Do_obejrzenia'},
        ),
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='obejrzane',
            options={'verbose_name_plural': 'Obejrzane'},
        ),
        migrations.AlterModelOptions(
            name='produkcje',
            options={'verbose_name_plural': 'Produkcje'},
        ),
        migrations.AlterModelOptions(
            name='rezencje',
            options={'verbose_name_plural': 'Rezencje'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownicy',
            options={'verbose_name_plural': 'Uzytkownicy'},
        ),
        migrations.AddField(
            model_name='produkcje',
            name='Plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty/'),
        ),
        migrations.AlterField(
            model_name='do_obejrzenia',
            name='ID_Produkcji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.produkcje', verbose_name='Nazwa Produkcji'),
        ),
        migrations.AlterField(
            model_name='do_obejrzenia',
            name='ID_Uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uzytkownicy', verbose_name='Nazwa Użytkownika'),
        ),
        migrations.AlterField(
            model_name='obejrzane',
            name='ID_Produkcji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.produkcje', verbose_name='Nazwa Produkcji'),
        ),
        migrations.AlterField(
            model_name='obejrzane',
            name='ID_Uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uzytkownicy', verbose_name='Nazwa Użytkownika'),
        ),
        migrations.AlterField(
            model_name='produkcje',
            name='ID_Kategorii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kategorie', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='rezencje',
            name='ID_Produkcji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.produkcje', verbose_name='Nazwa Produkcji'),
        ),
        migrations.AlterField(
            model_name='rezencje',
            name='ID_Uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uzytkownicy', verbose_name='Nazwa Użytkownika'),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='Haslo',
            field=models.CharField(max_length=128),
        ),
    ]
